### ISSUE TITLE
Support sound files

### ISSUE THREAD

**Issue by PanderMusubi** [lukesmurray/markdown-anki-decks#13]
Please support sounds, an example for markdown would be:

    [sound](sound.wav)

Here https://github.com/lukesmurray/markdown-anki-decks/blob/master/markdown_anki_decks/cli.py#L245 the following line needs to be added:

    source.rglob("*.wav"),

See also https://github.com/kerrickstaley/genanki#media-files to add `MyMedia`

**Comment by lukesmurray** [comment]
implemented in [1.1.0](https://pypi.org/project/markdown-anki-decks/1.1.0/)

**Comment by PanderMusubi** [comment]
Thanks, it works great!
